### ISSUE TITLE
Run ART host tests for oreo-mr1-release

### ISSUE THREAD

**Issue by senier** [Componolit/componolit#77]
Before updating the ART port to 8.1 (oreo-mr1-release branch) we should be able to run run all host tests for ART on a x86_64 machine.

**Comment by senier** [comment]
Steps done so far:

1. `repo init -u https://android.googlesource.com/platform/manifest -b oreo-mr1-release`
2. `repo sync -c`
3. `make build-art-host`
4. `make test-art-gtest-host`
5. `./art/test.py --host`

The last step results in errors (for all tests) like this:

```
['/media/ssd/senier/Android/AOSP/art/test/testrunner/testrunner.py', '--host']
[ 0% 1/6960 ] test-art-host-run-test-debug-prebuild-optimizing-no-relocate-ntrace-cms-checkjni-picimage-npictest-ndebuggable-no-jvmti-471-uninitialized-locals32 FAIL
/media/ssd/senier/Android/AOSP/art/test/run-test  --output-path /tmp/test-art-i6_0jurl/tmp7vt0xwga --always-clean --host --prebuild --optimizing --no-relocate --runtime-option -Xcheck:jni 471-uninitialized-locals
/media/ssd/senier/Android/AOSP/art/test/471-uninitialized-locals: building...
/media/ssd/senier/Android/AOSP/art/test/471-uninitialized-locals: FAILED!

#################### info
# Regression for the optimizing for crashes during compilation of methods which
# use values before initializing them.
#################### diffs
--- expected.txt        2018-02-22 00:53:50.331968039 +0100
+++ output.txt  2018-02-22 09:25:14.396231704 +0100
@@ -0,0 +1,7 @@
+./build: line 430: /media/ssd/senier/Android/AOSP/out/host/linux-x86/bin/smali: No such file or directory
+Failed to build in tmpdir=/tmp/test-art-i6_0jurl/tmp7vt0xwga from oldwd=/home/senier/Android/AOSP and cwd=/tmp/test-art-i6_0jurl/tmp7vt0xwga
+Non-canonical tmpdir was /tmp/test-art-i6_0jurl/tmp7vt0xwga
+Args: --output-path /tmp/test-art-i6_0jurl/tmp7vt0xwga --always-clean --host --prebuild --optimizing --no-relocate --runtime-option -Xcheck:jni 471-uninitialized-locals
+build exit status: 1
+Max filename (NAME_MAX): 255
+Max pathlength (PATH_MAX): 4096
####################

471-uninitialized-locals files deleted from host
```

There is a second set of tests which are gtest-based. Running them gives a different error:

```
./art/test.py --host -g
make -j -C /media/ssd/senier/Android/AOSP  test-art-host-gtest dist
make: Entering directory '/media/ssd/senier/Android/AOSP'
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
TARGET_PRODUCT=aosp_x86
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86
TARGET_ARCH_VARIANT=x86
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-3.16.0-5-amd64-x86_64-with-debian-8.10
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM1.171019.019
OUT_DIR=out
============================================
ninja: no work to do.
ninja: no work to do.
==14387==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
==14387==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps you're using ulimit -v
09:33:46 ckati failed with: signal: aborted
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1                                          
```

**Comment by senier** [comment]
The first issue is resolved by building smali before running the tests. The steps required to run the (non-gtest) host tests are:

1. `repo init -u https://android.googlesource.com/platform/manifest -b oreo-mr1-release`
2. `repo sync -c`
3. `make build-art-host test-art-gtest-host smali`
4. `./art/test.py --host`

No sure whether `build-art-host` and `test-art-gtest-host` are both required.

**Comment by senier** [comment]
Another issue:

```
+Exception in thread "main" java.lang.reflect.InvocationTargetException
+       at java.lang.reflect.Method.invoke(Native Method)
+       at Main.main(Main.java:45)
+Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.InMemoryDexClassLoader[DexPathList[[dex file "InMemoryDexFile[cookie=[0, 1464143040]]"],nativeLibraryDirectories=[/media/ssd/senier/Android/AOSP/out/host/linux-x86/lib]]] couldn't find "libarttestd.so"
+       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
+       at java.lang.System.loadLibrary(System.java:1657)
+       at Test.initialize(Test.java:22)
+       ... 2 more
####################
```

This is resolved by building `libarttestd`:

1. `repo init -u https://android.googlesource.com/platform/manifest -b oreo-mr1-release`
2. `repo sync -c`
3. `make build-art-host test-art-gtest-host smali libarttestd`
4. `./art/test.py --host`

**Comment by senier** [comment]
One more missing tool: `dexmerger`

**Comment by senier** [comment]
More missing files: dx, jasmin, hprof-conv, libtiagentd.so, libartagentd.so

Updated build steps:

1. `repo init -u https://android.googlesource.com/platform/manifest -b oreo-mr1-release`
2. `repo sync -c`
3. `make build-art-host test-art-gtest-host smali libarttestd dx jasmin hprof-conv libtiagentd libartagentd`
4. `./art/test.py --host`

**Comment by senier** [comment]
Gtests succeed completely. Some of the host tests fail, but as we won't port those at the moment I'd consider this issue closed.
